version: "2"
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

  clamav:
    image: "mkodockx/docker-clamav"
    environment: 
      - CLAMD_CONF_StreamMaxLength=4000M
    expose: 
      - 3310

  minio:
    image: "minio/minio"
    environment: 
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: ["minio", "server", "/data"]
    expose: 
      - 9000